# Actuator Endpunkte
management:
  endpoints:
    enabled-by-default: false
  #    web:
  #      exposure:
  #        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  server:
    port: 8079

logging:
  level:
    org:
      springframework: INFO

# Port für die Servlets
server:
  port: 8080


camel:
  servlet:
    mapping:
      # Basepath für Servlet-Endpunkt:
      # https://camel.apache.org/components/4.8.x/servlet-component.html#_spring_boot_auto_configuration
      context-path: /*
  main:
    tracing: false
  springboot:
    main-run-controller: true
