# Actuator Endpunkte
management:
  endpoints:
    access:
      default: none
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
    info:
      access: read_only
    prometheus:
      access: read_only
  server:
    port: 8079

logging:
  level:
    org:
      springframework: INFO

# Port für die Servlets
server:
  port: 8080


camel:
  servlet:
    mapping:
      # Basepath für Servlet-Endpunkt:
      # https://camel.apache.org/components/4.8.x/servlet-component.html#_spring_boot_auto_configuration
      context-path: /*
  main:
    tracing: false
  springboot:
    # Camel läuft in einer eigenen Spring-Boot-Instanz
    # https://camel.apache.org/camel-spring-boot/4.8.x/index.html#_making_sure_camel_context_is_running_in_standalone_spring_boot
    main-run-controller: true
